# generator_4_1.py

import genanki

model = genanki.Model(
  1607392320,
  'PADI Model 4.1',
  fields=[
    {'name': 'Question'},
    {'name': 'Answer'}
  ],
  templates=[
    {
      'name': 'Card 1',
      'qfmt': '{{Question}}',
      'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}'
    }
  ]
)

deck = genanki.Deck(
  2059400111,
  'PADI IDC pytania 2025::4.1 standardy cz 1. abcd'
)

questions = [
  ["4.1.1. Kto może być certyfikowanym asystentem ?\na)PADI Divemaster, PADI Asystent Instruktora\nb)PADI  Asystent Instruktora, PADI Instruktor\nc)PADI Rescue Diver z rozpoczętym kursem Divemastera\nd)odpowiedzi a i b są poprawne", "Odpowiedź: **d) odpowiedzi a i b są poprawne**\nWyjaśnienie: Zarówno PADI Divemaster, jak i Asystent Instruktora są uznawani za certyfikowanych asystentów w systemie PADI."],
  ["4.1.2. Podaj maksymalną dopuszczalną głębokość nurkowań na kursach:\na)Open Water Diver\nb)Advanced Open Water\nc)Specjalizacja Głęboka\nd)Junior Advanced Open Water", "Odpowiedź: **a) Open Water Diver**\nWyjaśnienie: Dla kursu OWD maksymalna głębokość to 18 m; inne odpowiedzi wymagają doprecyzowania i nie stanowią kompletnego pytania wielokrotnego wyboru."],
  ["4.1.3. Ilość nurkowań wymaganych aby zaliczyć podane niżej kursy:\na)Open Water Diver\nb)Advanced Open Water\nc)Specjalizacja sidemount\nd)Specjalizacja podlodowa", "Odpowiedź: **a) Open Water Diver**\nWyjaśnienie: Kurs OWD wymaga co najmniej 4 nurkowań szkoleniowych, AOWD – 5, sidemount i podlodowa zazwyczaj 2–3."],
  ["4.1.4. Ile ćwiczeń wymaganych jest podczas kursu Rescue Diver:\na)5\nb)ilość ćwiczeń zależy od instruktora\nc)10\nd)9", "Odpowiedź: **d) 9**\nWyjaśnienie: Kurs Rescue Diver zawiera 10 scenariuszy, ale wymagane są 9 ćwiczeń podstawowych."],
  ["4.1.5. Maksymalna głębokość podczas nurkowania w wodzie otwartej na programie Discover Scuba Diving wynosi:\na)9 m\nb)18 m\nc)w trakcie tego programu nie ma zajęć na wodzie otwartej\nd)12 m", "Odpowiedź: **a) 9 m**\nWyjaśnienie: W programie DSD maksymalna głębokość na wodach otwartych to 12 m, jednak zaleca się nie przekraczać 9 m."],
  ["4.1.6. PIC powinien być wysłany:\na)w ciągu 7-miu dni od rozpoczęcia kursu\nb)jeżeli kursant tylko zapłacił za kurs\nc)jeżeli kursant spełnił wszystkie wymagania zaliczeniowe kursu\nd)odpowiedzi a i b są właściwe", "Odpowiedź: **c) jeżeli kursant spełnił wszystkie wymagania zaliczeniowe kursu**\nWyjaśnienie: PIC (Positive Identification Card) wysyła się po zakończeniu i zaliczeniu kursu przez kursanta."],
  ["4.1.7. Co musi udokumentować nurek aby jego stopień w innej organizacji uznać za stopień równoważny z PADI Open Water Diver?\na)5 nurkowań\nb)4 nurkowania szkoleniowe i podstawowy stopień nurkowy\nc)minimum 20 nurkowań w tym jedno głębokie i jedno nawigacyjne\nd)2 lata nurkowania bez certyfikatu i 20 udokumentowanych nurkowań", "Odpowiedź: **b) 4 nurkowania szkoleniowe i podstawowy stopień nurkowy**\nWyjaśnienie: PADI uznaje równoważność na podstawie szkoleniowego programu i dokumentacji szkolenia."],
  ["4.1.8. Ile metod sztucznego oddychania musisz zrobić ze studentami prowadząc kurs PADI Rescue Diver?\na)w zależności od lokalnego prawa\nb)zależy czy jest to na certyfikat junior Rescue Diver\nc)2\nd)12 ćwiczeń", "Odpowiedź: **a) w zależności od lokalnego prawa**\nWyjaśnienie: PADI dostosowuje wymagania do lokalnych przepisów medycznych i prawnych."],
  ["4.1.9. Prawda czy Fałsz ?\nSystem instruktażowy szkolenia nurków może być określony jako zestaw powiązanych, współpracujących środków dydaktycznych, przeznaczonych do realizacji określonego celu.", "Odpowiedź: **Prawda**\nWyjaśnienie: System PADI opiera się na ustrukturyzowanym podejściu z jasno określonymi celami edukacyjnymi."],
  ["4.1.10. Przed przystąpieniem do kursu na Divemastera kandydat musi posiadać:\na)PADI Rescue Diver i 60 nurkowań\nb)Advanced Open Water Diver, Rescue Diver i 60 udokumentowanych nurkowań\nc)PADI Rescue Diver i 20 udokumentowanych nurkowań\nd)PADI Advanced Diver i PADI Rescue Diver lub równoważne oraz 20 udokumentowanych nurkowań", "Odpowiedź: **b) Advanced Open Water Diver, Rescue Diver i 60 udokumentowanych nurkowań**\nWyjaśnienie: Są to minimalne wymagania do rozpoczęcia kursu PADI Divemaster."],
  ["4.1.11. Kto może prowadzić program Discover Scuba Diving?\na)Tylko certyfikowany instruktor\nb)Divemaster pod bezpośrednim nadzorem instruktora\nc)Każdy z doświadczeniem nurkowym\nd)Asystent instruktora bez nadzoru", "Odpowiedź: **b) Divemaster pod bezpośrednim nadzorem instruktora**\nWyjaśnienie: Divemaster może prowadzić DSD tylko pod bezpośrednim nadzorem PADI Instruktora."],
  ["4.1.12. Ile wynosi maksymalna liczba studentów na jednego instruktora podczas ćwiczeń na wodach otwartych?\na)6\nb)8\nc)10\nd)12", "Odpowiedź: **a) 6**\nWyjaśnienie: Zalecenia PADI określają maksymalny stosunek 1:6 na wodach otwartych dla bezpieczeństwa."],
  ["4.1.13. Kto może prowadzić program PADI Seal Team?\na)PADI Instructor\nb)PADI Divemaster\nc)PADI Assistant Instructor\nd)PADI Master Instructor", "Odpowiedź: **a) PADI Instructor**\nWyjaśnienie: Program Seal Team może prowadzić tylko certyfikowany PADI Instructor."],
  ["4.1.14. Jaki jest minimalny wiek do rozpoczęcia kursu OWD?\na)10 lat\nb)12 lat\nc)14 lat\nd)16 lat", "Odpowiedź: **a) 10 lat**\nWyjaśnienie: Minimalny wiek dla Junior OWD to 10 lat, dla pełnego OWD - 15 lat."],
  ["4.1.15. Minimalna widoczność podczas ćwiczeń na wodach otwartych to:\na)1 metr\nb)2 metry\nc)3 metry\nd)nie określono", "Odpowiedź: **b) 2 metry**\nWyjaśnienie: PADI zaleca minimalną widoczność 2 metry dla bezpieczeństwa i efektywności szkolenia."],
  ["4.1.16. Co oznacza skrót CW?\na)Cold Water\nb)Confined Water\nc)Certified Wreck\nd)Compressed Water", "Odpowiedź: **b) Confined Water**\nWyjaśnienie: CW oznacza środowisko ograniczone, np. basen lub warunki basenopodobne używane w szkoleniach."],
  ["4.1.17. Ile sesji na wodach ograniczonych przewiduje kurs Open Water Diver?\na)3\nb)4\nc)5\nd)6", "Odpowiedź: **c) 5**\nWyjaśnienie: Kurs OWD standardowo obejmuje 5 sesji CW, które można połączyć w minimum 2 spotkania."],
  ["4.1.18. Kiedy należy przeprowadzić quizy w kursie OWD?\na)po nurkowaniu\nb)po przeczytaniu podręcznika\nc)po obejrzeniu materiału video\nd)po zakończeniu kursu", "Odpowiedź: **c) po obejrzeniu materiału video**\nWyjaśnienie: Quizy są zgodne z materiałem video i służą do sprawdzenia wiedzy po każdym rozdziale."],
  ["4.1.19. Kto może zatwierdzić nurkowanie w programie Discover Scuba Diving?\na)Divemaster\nb)Asystent instruktora\nc)Tylko instruktor\nd)Każdy certyfikowany nurek", "Odpowiedź: **c) Tylko instruktor**\nWyjaśnienie: Odpowiedzialność formalna spoczywa wyłącznie na instruktorze prowadzącym program."],
  ["4.1.20. Jakie dokumenty musi posiadać kursant przed rozpoczęciem kursu OWD?\na)podpisany formularz medyczny, zgoda rodziców (jeśli niepełnoletni), rejestr nurkowań\nb)zaświadczenie lekarskie, formularz RSTC, zdjęcie\nc)formularz medyczny, zgoda rodzica, rejestr nurkowań\nd)formularz medyczny i zgoda na przetwarzanie danych", "Odpowiedź: **a) podpisany formularz medyczny, zgoda rodziców (jeśli niepełnoletni), rejestr nurkowań**\nWyjaśnienie: To podstawowy zestaw dokumentów wymaganych przed rozpoczęciem szkolenia."],
  ["4.1.21. Kiedy należy przeprowadzić scenariusze ratownicze w Rescue Diver?\na)po ćwiczeniach podstawowych\nb)na początku kursu\nc)po pierwszym nurkowaniu\nd)przed egzaminem końcowym", "Odpowiedź: **a) po ćwiczeniach podstawowych**\nWyjaśnienie: Scenariusze wymagają wcześniejszego opanowania umiejętności bazowych."],
  ["4.1.22. Ile trwa standardowy wykład akademicki w kursie AOWD?\na)20 min\nb)30–45 min\nc)nie określono\nd)poniżej 15 min", "Odpowiedź: **c) nie określono**\nWyjaśnienie: AOWD kładzie nacisk na naukę w działaniu, a nie na wykłady – nie ma sztywnych ram czasowych."],
  ["4.1.23. Kiedy można użyć materiałów cyfrowych w kursie OWD?\na)zawsze\nb)tylko przed zajęciami praktycznymi\nc)jeśli kursant nie ma podręcznika papierowego\nd)w zależności od preferencji instruktora", "Odpowiedź: **a) zawsze**\nWyjaśnienie: PADI dopuszcza użycie materiałów cyfrowych jako równoważne wersji drukowanej w całym kursie."],
  ["4.1.24. Ile trwa sesja briefingu i debriefingu razem przed i po nurkowaniu?\na)5 minut\nb)około 15 minut\nc)30 minut\nd)zależy od instruktora", "Odpowiedź: **b) około 15 minut**\nWyjaśnienie: Zalecany czas na omówienie planu nurkowania i późniejszy feedback to około 15 minut łącznie."],
  ["4.1.25. Kto ponosi odpowiedzialność za bezpieczeństwo studentów w wodzie?\na)student\nb)Divemaster\nc)instruktor prowadzący\nd)każdy certyfikowany nurek", "Odpowiedź: **c) instruktor prowadzący**\nWyjaśnienie: PADI jednoznacznie przypisuje odpowiedzialność za szkolenie i bezpieczeństwo instruktorowi."],
  ["4.1.26. Co oznacza skrót RDP?\na)Recreational Dive Plan\nb)Recreational Dive Planner\nc)Rapid Dive Protocol\nd)Repetitive Dive Planner", "Odpowiedź: **b) Recreational Dive Planner**\nWyjaśnienie: RDP to tabelaryczne narzędzie planowania nurkowań bezdekompresyjnych."],
  ["4.1.27. Jakie są dopuszczalne środki nauczania na wodach ograniczonych?\na)tylko prezentacja umiejętności\nb)prezentacja i powtarzanie przez kursanta\nc)ćwiczenia i teoria\nd)film instruktażowy", "Odpowiedź: **b) prezentacja i powtarzanie przez kursanta**\nWyjaśnienie: Celem jest opanowanie umiejętności poprzez pokaz i aktywne ćwiczenie."],
  ["4.1.28. W jakiej kolejności przeprowadza się ćwiczenia ratownicze?\na)losowo\nb)według scenariuszy\nc)zgodnie z kolejnością zalecaną przez PADI\nd)według warunków pogodowych", "Odpowiedź: **c) zgodnie z kolejnością zalecaną przez PADI**\nWyjaśnienie: PADI zaleca konkretną sekwencję ćwiczeń w Rescue Diver dla progresji nauczania."],
  ["4.1.29. Kiedy można łączyć sesje CW?\na)gdy student nie ma czasu\nb)gdy wszystkie umiejętności zostały wcześniej opanowane\nc)jeśli nie ma basenu\nd)jeśli nie zakłóca to procesu uczenia", "Odpowiedź: **d) jeśli nie zakłóca to procesu uczenia**\nWyjaśnienie: Łączenie sesji jest możliwe, ale nie może ograniczyć jakości nauczania."],
  ["4.1.30. Czy można używać tylko materiałów po angielsku?\na)tak\nb)tylko w krajach anglojęzycznych\nc)nie, należy używać wersji w języku kursanta\nd)tak, jeśli kursant się zgodzi", "Odpowiedź: **c) nie, należy używać wersji w języku kursanta**\nWyjaśnienie: Materiały muszą być zrozumiałe – język kursanta jest podstawowym kryterium."],
  ["4.1.31. Ile wynosi minimalna temperatura wody do przeprowadzenia ćwiczeń na wodach ograniczonych?\na)10°C\nb)15°C\nc)20°C\nd)nie określono", "Odpowiedź: **d) nie określono**\nWyjaśnienie: PADI nie definiuje konkretnej temperatury, ale instruktor ma obowiązek zapewnić komfort i bezpieczeństwo studentów."],
  ["4.1.32. Jaki jest główny cel programu PADI Scuba Diver?\na)Wprowadzenie do sprzętu nurkowego\nb)Uzyskanie pełnych uprawnień OWD\nc)Pozwolenie na nurkowanie do 12 m pod nadzorem\nd)Zdobycie umiejętności planowania nurkowań", "Odpowiedź: **c) Pozwolenie na nurkowanie do 12 m pod nadzorem**\nWyjaśnienie: PADI Scuba Diver to skrócona wersja OWD pozwalająca na nurkowanie z profesjonalistą do 12 m."],
  ["4.1.33. Ile scenariuszy ratowniczych należy zrealizować na kursie Rescue Diver?\na)1\nb)2\nc)3\nd)4", "Odpowiedź: **b) 2**\nWyjaśnienie: W kursie Rescue Diver obowiązkowe są dwa scenariusze ratownicze przeprowadzane po zakończeniu ćwiczeń podstawowych."],
  ["4.1.34. Czy można przeprowadzić kurs OWD bez materiałów PADI?\na)tak\nb)tak, jeśli instruktor ma własne\nc)nie\nd)tak, jeśli kursant się zgodzi", "Odpowiedź: **c) nie**\nWyjaśnienie: Korzystanie z zatwierdzonych materiałów PADI jest obowiązkowe zgodnie ze standardami szkoleniowymi."],
  ["4.1.35. Jaki dokument potwierdza certyfikację kursanta po kursie?\na)Kopia logbooka\nb)Kopia formularza medycznego\nc)PIC\nd)Certyfikat medyczny", "Odpowiedź: **c) PIC**\nWyjaśnienie: PIC (Positive Identification Card) to formularz niezbędny do wystawienia certyfikatu kursantowi."],
  ["4.1.36. Jakie jest ograniczenie wiekowe do udziału w kursie Junior OWD?\na)8 lat\nb)10 lat\nc)12 lat\nd)14 lat", "Odpowiedź: **b) 10 lat**\nWyjaśnienie: Minimalny wiek dla Junior OWD to 10 lat, z odpowiednimi ograniczeniami głębokości."],
  ["4.1.37. Kiedy można prowadzić nurkowanie z prądem jako Adventure Dive?\na)po kursie Deep\nb)po kursie Rescue\nc)po zaliczeniu teorii i briefingu prądowego\nd)po 20 nurkowaniach", "Odpowiedź: **c) po zaliczeniu teorii i briefingu prądowego**\nWyjaśnienie: Adventure Dive z prądem wymaga wcześniejszego przygotowania teoretycznego."],
  ["4.1.38. Ile maksymalnie studentów może przypadać na jednego instruktora podczas kursu AOWD?\na)4\nb)6\nc)8\nd)nie określono", "Odpowiedź: **c) 8**\nWyjaśnienie: Standardy PADI dla AOWD przewidują maksymalny stosunek 1:8 pod warunkiem zapewnienia bezpieczeństwa."],
  ["4.1.39. Czy Divemaster może prowadzić kursy specjalistyczne?\na)tak\nb)nie\nc)tak, tylko pod nadzorem instruktora\nd)tak, jeśli ma zgodę centrum nurkowego", "Odpowiedź: **b) nie**\nWyjaśnienie: Tylko instruktorzy PADI mogą prowadzić kursy specjalistyczne i wystawiać certyfikaty."],
  ["4.1.40. Jakie jest minimalne doświadczenie instruktora do prowadzenia kursu AOWD?\na)25 certyfikacji\nb)50 certyfikacji\nc)100 nurkowań\nd)bycie instruktorem aktywnym", "Odpowiedź: **d) bycie instruktorem aktywnym**\nWyjaśnienie: Instruktor musi mieć status aktywny, bez wymaganego progu certyfikacji, by prowadzić AOWD."],
  ["4.1.41. Co musi zawierać szkolenie e-learning OWD?\na)Test końcowy i quizy\nb)Wyłącznie materiał video\nc)Tylko książkę PDF\nd)Nie zawiera żadnych materiałów interaktywnych", "Odpowiedź: **a) Test końcowy i quizy**\nWyjaśnienie: E-learning OWD zawiera wbudowane quizy i egzamin końcowy jako integralne części szkolenia."],
  ["4.1.42. Kiedy można rozpocząć kurs Rescue Diver?\na)po uzyskaniu AOWD i EFR\nb)po OWD i 20 nurkowaniach\nc)po specjalizacji głębokiej\nd)po kursie Scuba Diver", "Odpowiedź: **a) po uzyskaniu AOWD i EFR**\nWyjaśnienie: Są to wymagania wstępne do rozpoczęcia kursu Rescue Diver."],
  ["4.1.43. Co oznacza skrót EFR?\na)Emergency First Response\nb)Emergency Fast Rescue\nc)Evaluation For Rescue\nd)Emergency Free Rescue", "Odpowiedź: **a) Emergency First Response**\nWyjaśnienie: EFR to szkolenie z zakresu pierwszej pomocy wymagane m.in. przed kursem Rescue Diver."],
  ["4.1.44. Ile maksymalnie osób może brać udział w zajęciach basenowych na kursie OWD?\na)6\nb)8\nc)10\nd)12", "Odpowiedź: **a) 6**\nWyjaśnienie: Dla CW (Confined Water) maksymalny stosunek to 1:6 dla bezpieczeństwa i skuteczności nauczania."],
  ["4.1.45. Ile czasu ważny jest formularz medyczny PADI, jeśli nie ma przeciwwskazań?\na)6 miesięcy\nb)12 miesięcy\nc)nieograniczenie\nd)do końca roku kalendarzowego", "Odpowiedź: **b) 12 miesięcy**\nWyjaśnienie: Formularz medyczny PADI jest ważny przez 12 miesięcy od daty podpisu lekarza lub kursanta (jeśli bez przeciwwskazań)."],
  ["4.1.46. Czy Divemaster może prowadzić briefing przed nurkowaniem AOWD?\na)tak\nb)nie\nc)tak, tylko pod nadzorem instruktora\nd)tylko jeśli ma uprawnienia EFR", "Odpowiedź: **a) tak**\nWyjaśnienie: Divemaster może przeprowadzać briefing pod warunkiem, że instruktor pozostaje odpowiedzialny za szkolenie."],
  ["4.1.47. Jaki typ pytania NIE występuje na egzaminie końcowym kursu OWD?\na)ABCD wielokrotnego wyboru\nb)prawda/fałsz\nc)uzupełnianie luk\nd)wybór obrazka", "Odpowiedź: **d) wybór obrazka**\nWyjaśnienie: Egzamin składa się wyłącznie z pytań ABCD i Prawda/Fałsz."],
  ["4.1.48. Czy można przeprowadzić kurs Rescue Diver bez wcześniejszego EFR?\na)tak, jeśli kursant ma własne doświadczenie\nb)tak, jeśli jest ratownikiem WOPR\nc)nie\nd)tak, jeśli uzgodni z instruktorem", "Odpowiedź: **c) nie**\nWyjaśnienie: EFR lub równoważny kurs z ostatnich 24 miesięcy jest obowiązkowy przed rozpoczęciem Rescue."],
  ["4.1.49. Ile dni można maksymalnie odłożyć kontynuację kursu OWD?\na)90\nb)180\nc)365\nd)nie określono", "Odpowiedź: **d) nie określono**\nWyjaśnienie: Nie ma formalnego limitu w standardach, ale instruktor powinien zadbać o zachowanie ciągłości szkolenia."],
  ["4.1.50. Co oznacza termin \"ratownictwo reagujące na stres\"?\na)Reakcję na własne emocje pod wodą\nb)Analizę stresu nurka\nc)Szybką reakcję na problemy związane z paniką\nd)Zgłaszanie sytuacji awaryjnej do instruktora", "Odpowiedź: **c) Szybką reakcję na problemy związane z paniką**\nWyjaśnienie: Pojęcie odnosi się do scenariuszy ratowniczych związanych z reakcją na stres i panikę u nurka."],
  ["4.1.51. Kiedy Divemaster może nadzorować studentów OWD?\na)podczas zajęć teoretycznych\nb)na wodach otwartych, pod bezpośrednim nadzorem instruktora\nc)na wodach basenowych samodzielnie\nd)w każdej sytuacji po uzgodnieniu z instruktorem", "Odpowiedź: **b) na wodach otwartych, pod bezpośrednim nadzorem instruktora**\nWyjaśnienie: Divemaster może nadzorować studentów OWD jedynie pod bezpośrednim nadzorem instruktora."],
  ["4.1.52. Jak długo ważne są certyfikaty PADI?\na)12 miesięcy\nb)bezterminowo\nc)do momentu ukończenia kolejnego kursu\nd)5 lat", "Odpowiedź: **b) bezterminowo**\nWyjaśnienie: Certyfikaty PADI nie wygasają, ale aktywność i doświadczenie mogą wpływać na dopuszczenie do zaawansowanych kursów."],
  ["4.1.53. Kto odpowiada za przestrzeganie standardów podczas kursu?\na)student\nb)centrum nurkowe\nc)instruktor prowadzący\nd)Divemaster", "Odpowiedź: **c) instruktor prowadzący**\nWyjaśnienie: Instruktor ponosi pełną odpowiedzialność za zgodność kursu ze standardami PADI."],
  ["4.1.54. Ile dni musi minąć między dwoma nurkowaniami głębokimi (poniżej 30 m)?\na)1 dzień\nb)nie ma określonego limitu\nc)7 dni\nd)3 dni", "Odpowiedź: **b) nie ma określonego limitu**\nWyjaśnienie: PADI nie narzuca przerwy czasowej, ale każde nurkowanie głębokie wymaga szczególnego planowania i oceny ryzyka."],
  ["4.1.55. Jakie ćwiczenia należy przeprowadzić na wodach ograniczonych w kursie OWD?\na)pełen zestaw ćwiczeń PADI dla OWD\nb)tylko ćwiczenia z maską i oddechem\nc)ćwiczenia zależne od instruktora\nd)tylko briefing i wejście do wody", "Odpowiedź: **a) pełen zestaw ćwiczeń PADI dla OWD**\nWyjaśnienie: Wszystkie wymagane ćwiczenia muszą zostać przeprowadzone na CW przed wodami otwartymi."],
  ["4.1.56. Co jest podstawowym celem kursu Rescue Diver?\na)Nauczyć nurka pracy z partnerem\nb)Zwiększyć komfort podczas głębokich nurkowań\nc)Rozwój umiejętności rozpoznawania i reagowania na sytuacje awaryjne\nd)Podstawy pierwszej pomocy", "Odpowiedź: **c) Rozwój umiejętności rozpoznawania i reagowania na sytuacje awaryjne**\nWyjaśnienie: Rescue Diver skupia się na reagowaniu na problemy nurków pod wodą i na powierzchni."],
  ["4.1.57. Co musi zawierać dokumentacja kursanta?\na)Logbook, formularz medyczny, zapis szkolenia\nb)Tylko certyfikat\nc)Dowód opłaty\nd)E-mail potwierdzający udział", "Odpowiedź: **a) Logbook, formularz medyczny, zapis szkolenia**\nWyjaśnienie: Instruktor musi przechowywać pełną dokumentację potwierdzającą zgodność kursu ze standardami."],
  ["4.1.58. Czy instruktor może samodzielnie zmodyfikować standardy PADI?\na)tak\nb)nie\nc)tak, jeśli dotyczy to CW\nd)tylko po zatwierdzeniu przez biuro regionalne", "Odpowiedź: **b) nie**\nWyjaśnienie: Standardy PADI są obowiązujące i niepodlegające dowolnej modyfikacji przez instruktora."],
  ["4.1.59. Ile maksymalnie godzin może trwać dzienny program szkoleniowy?\na)4 godziny\nb)6 godzin\nc)8 godzin\nd)zgodnie z oceną instruktora", "Odpowiedź: **d) zgodnie z oceną instruktora**\nWyjaśnienie: Nie ma sztywnego limitu, ale instruktor musi ocenić zmęczenie i bezpieczeństwo studentów."],
  ["4.1.60. Kiedy student może przejść na poziom Advanced Open Water?\na)po ukończeniu OWD\nb)po 10 nurkowaniach\nc)po specjalizacji głębokiej\nd)po kursie Rescue", "Odpowiedź: **a) po ukończeniu OWD**\nWyjaśnienie: Warunkiem przystąpienia do AOWD jest posiadanie certyfikatu OWD."],
  ["4.1.61. Czy student może korzystać z e-learningu PADI na telefonie?\na)tak\nb)nie\nc)tylko na komputerze\nd)tylko w centrum nurkowym", "Odpowiedź: **a) tak**\nWyjaśnienie: E-learning PADI jest dostępny na różnych urządzeniach, w tym telefonach, tabletach i komputerach."],
  ["4.1.62. Kto może przeprowadzić kurs Emergency Oxygen Provider?\na)EFR Instructor\nb)Divemaster\nc)PADI Instructor\nd)każdy, kto ukończył kurs", "Odpowiedź: **c) PADI Instructor**\nWyjaśnienie: Tylko certyfikowany PADI Instructor może przeprowadzać ten kurs i wystawiać certyfikaty."],
  ["4.1.63. Co oznacza skrót CW?\na)Cold Water\nb)Confined Water\nc)Course Work\nd)Certified Workshop", "Odpowiedź: **b) Confined Water**\nWyjaśnienie: CW oznacza środowisko kontrolowane (np. basen) używane do ćwiczeń nurkowych."],
  ["4.1.64. Czy PADI dopuszcza indywidualne nauczanie kursanta?\na)tak\nb)nie\nc)tylko w CW\nd)tylko na poziomie AOWD", "Odpowiedź: **a) tak**\nWyjaśnienie: Indywidualne szkolenie jest dozwolone, o ile spełnia wszystkie wymagania standardów."],
  ["4.1.65. Ile certyfikacji musi mieć instruktor, aby uzyskać tytuł Master Scuba Diver Trainer?\na)10\nb)25\nc)50\nd)100", "Odpowiedź: **b) 25**\nWyjaśnienie: Aby zostać MSDT, instruktor musi mieć 25 certyfikacji i minimum 5 specjalizacji instruktorskich."],
  ["4.1.66. Czy Junior OWD może nurkować do 18 m?\na)tak\nb)nie\nc)tak, jeśli ukończył 13 lat\nd)tylko z instruktorem", "Odpowiedź: **b) nie**\nWyjaśnienie: Junior OWD mają ograniczenie do 12 m, które obowiązuje do ukończenia odpowiedniego wieku."],
  ["4.1.67. Jakie są limity głębokości dla AOWD?\na)18 m\nb)30 m\nc)21 m\nd)bez limitu", "Odpowiedź: **b) 30 m**\nWyjaśnienie: Certyfikat AOWD uprawnia do nurkowań rekreacyjnych do maksymalnej głębokości 30 metrów."],
  ["4.1.68. Kiedy można zaliczyć specjalizację w nurkowaniu nocnym?\na)po jednym nurkowaniu nocnym\nb)po 2 nurkowaniach\nc)po 3 nurkowaniach\nd)po teorii i 1 nurkowaniu", "Odpowiedź: **c) po 3 nurkowaniach**\nWyjaśnienie: Kurs PADI Night Diver wymaga 3 nurkowań nocnych jako część programu szkoleniowego."],
  ["4.1.69. Czy student musi mieć własny komputer nurkowy na kursie AOWD?\na)tak\nb)nie\nc)tylko jeśli instruktor tak zaleci\nd)w zależności od regionu", "Odpowiedź: **b) nie**\nWyjaśnienie: Student nie musi mieć własnego komputera, ale musi mieć dostęp do urządzenia do planowania i monitorowania nurkowań."],
  ["4.1.70. Jak długo należy przechowywać dokumentację kursu?\na)6 miesięcy\nb)1 rok\nc)7 lat\nd)3 lata", "Odpowiedź: **c) 7 lat**\nWyjaśnienie: PADI wymaga, aby dokumentacja kursu była przechowywana przez minimum 7 lat od zakończenia szkolenia."]
]

for q in questions:
  note = genanki.Note(
    model=model,
    fields=q
  )
  deck.add_note(note)

genanki.Package(deck).write_to_file('padi_idc_4_1_standardy.apkg')
print("✅ Deck 'padi_idc_4_1_standardy.apkg' has been generated.")
